### ISSUE TITLE
TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by Zezeneka** [NoxCaos/amusement-club#126]
![image](https://user-images.githubusercontent.com/42508727/72981248-efb06300-3e0e-11ea-810d-a8c3303f3c9a.png)

**Comment by NoxCaos** [comment]
Is your database populated with some cards?
The test data has the issue that it has more collections than there are cards. Try removing all collections except one that 100% has a card

**Comment by Zezeneka** [comment]
no i did remove all pf them, and i use ayano to update the collections of the card

**Comment by NoxCaos** [comment]
Check if user's 'cards' array has nulls. Either this or your claim card is null for some reason

**Comment by Zezeneka** [comment]
ah yes its null, how to fix it?

**Comment by Zezeneka** [comment]
![image](https://user-images.githubusercontent.com/42508727/73271780-d2ff9b00-4213-11ea-9062-e625518a774c.png)

**Comment by Zezeneka** [comment]
Even i already fix the collections its still show null lmai

**Comment by NoxCaos** [comment]
Sorry I don't think this belongs in issues since it doesn't seem like a bot issue.
If you want me to help you quicker just contact me over discord
