### ISSUE TITLE
hero subname is not replaced when switching heroes

### ISSUE THREAD

**Issue by Ruchian** [NoxCaos/amusement-club#66]
I already mentioned this on the discord. Basically what happens is that when a hero is changed, the hero name and image are replaced, but the subname is not. The result is that you get strange combinations like: Dark Priestress Akaza Akari or Anti-Bully Ranger Yoshikawa Chinatsu,

I suspect this happens because of what the function `"switchHero"` does in
[amusement-club/modules/heroes.js](https://github.com/NoxCaos/amusement-club/blob/master/modules/heroes.js)
It actively sets the new hero's name into the database replacing the older one, but this does not happen with the subname from what I can tell. Because of this, I think the database grabs the subname it was assigned to when the user obtained their hero for the first time. I figured at least that upon loading `"getHero"`, the database, instead of `heroes.json`, is searched for the entries of `hero.name` and `hero.subname`.

To be fair, I do not have any programming knowledge. I used my head while trying to read and to understand a bit of the code and I made my conclusion here based on what I get from the entries you wrote there. Therefore I could be entirely mistaken as to how this works, but in any case I do hope it is helpful.
Actually, if I get it right, all you need to do is make a small change to the var entry there, adding something that updates the hero subname as well, like `"hero.subname" : newHero.subname,` or so I figured.

**Comment by NoxCaos** [comment]
Thank you for reporting the issue and researching it. I will take a look asap

**Comment by NoxCaos** [comment]
Fixed in https://github.com/NoxCaos/amusement-club/commit/589ea5d916bfc14a8da63289eb656426f712aa03
