### ISSUE TITLE
[request] rebalance suggestion

### ISSUE THREAD

**Issue by Ruchian** [NoxCaos/amusement-club#67]
This may have been mentioned somewhere already, but I decided to inform you of this anyway.

Currently, a daily claim gives 300 Tomatoes.
A quest either rewards 400, 500 or 650 tomatoes by default. (minimum reward is 800)
Chinatsu boosts quest rewards by 80%, making her minimum quest reward 720x3 (as she receives an extra quest as well), so 2160. 
Yui's effect gives +100 daily tomatoes for every card previously claimed.
Akari's effect makes claim cost 65% of original price.

Claim costs are 50 times number of cards previously claimed + 1.
So you get a table like this.

claim | cost common | total | cost akari | total | comment
----- | -------------- | ----- | --------- | ----- | ----------
1 | 50 | 50 | 32.5 | 32.5 |
2 | 100 | 150 | 65 | 97.5 |
3 | 150 | 300 | 97.5 | 195 | common daily gone
4 | 200 | 500 | 130 | 325 | akari daily gone
5 | 250 | 750 | 162.5 | 487.5 |
6 | 300 | 1050 | 195 | 682.5 |
7 | 350 | 1400 | 227.5 | 910 | kyoko debt
8 | 400 | 1800 | 260 | 1170 | akari debt
9 | 450 | 2250 | 292.5 | 1462.5 | yui debt
10 | 500 | 2750 | 325 | 1787.5 | chinatsu debt

When I commented on the debt, I mean when at minimum quest reward, people would claim more than they can affort (when their tomato stock is empty) Yui scores second highest because of her +100 per card. The difference between Yui and Chinatsu's debt is also interesting. 
Trying to claim the 10th card, chinatsu would be 290 tomatoes short. Trying to claim the 9th card, Yui would be 250 tomatoes short.

I understand Kyoko's cost is lower because of her two other effects, making her a more strategic auctioner hero, but considering Akari only has the effect of reducing claim cost, it's strange that she is only one card better off than Kyoko. Yui also has the second effect of making all effect cards have half their cooldown. 

So, to conclude: With Yui, not only can you reliably claim a large amount of cards with her while still holding on a nice stockpile of tomatoes for later bidding on the auction, the reduced time for an effect card's activation makes her pretty much overpowered compared to the others. It effectively makes her the best choice for hero and to such point that there seems to be little reason to pick another one. Perhaps chinatsu to more quickly stockpile tomatoes, but Akari is practically useless this way and Kyoko is more for those who are already rich.

I was wondering if you could rebalance things a bit. At least between Yui and Akari. You could  consider to decrease the card cost for akari even further so she has better benefits or add a second hero effect for her. It would result in more players pick her and I mean not just for the looks.

**Comment by NoxCaos** [comment]
Thank you for the research and detailed report. I am aware that there are a lot of balance issues with heroes. Mostly because a lot of abilities were changed/removed as game changed a lot since heroes were implemented.
However, as I already mentioned before, there are no changes planned to the *current* hero system. There is new system planned and being implemented really slowly. Unfortunately I don't have enough time to sit down and work on it right now, so this will probably remain unresolved for some time.
But thank you again for your research, I appreciate the effort

**Comment by Ruchian** [comment]
Ah, I see. I just now found the post in which you mentioned this thanks to the system keyword. You mentioned it over a year ago. Sorry, I completely missed this message before (despite searching).
I'm not in a hurry to see changes or anything. I just wanted to inform you of something that I happen to notice while I was trying out heroes and wanted to take a closer look at the numbers while at it, thinking it may be useful for something. 
Take all the time you need. I'm pretty certain, especially after reading the announcements you made yesterday that your life is busy enough even without this.
